### PR TITLE
Python Extension Implementation

### PR DESCRIPTION
**Pull request by Chippyri**
This is a suggestion to review and/or merge the Python Extension discussed in Issue #16 . Since this is our (me and my team member's) first pull request to someone else's project on GitHub, I hope the result is thoroughly scrutinized.

A class that inherits from Solver has been created in Solver_Py.
It can be instantiated by using the argument ```-l py``` when running Include Gardener. 

Statement_Py is an object that analyzes an import statement in its constructor and allows Solver_Py to extract information about the statement with getters. If a statement contains multiple imports then it is split in to further Statement_Py-children in Statement_Py. 

Other previously present classes should not have been modified but the Solver-factory in Solver and possibly main.

**What is supported:**
1. imports on the form "import x" and "from x import y" 
2. absolute and relative imports
3. comma-separated imports
4. as-statements are allowed (but removed!)
5. imports on the form "from x import *" reads \_\_all\_\_ in \_\_init\_\_.py

**Important to know:**
- The first path given is treated as the root from where to resolve absolute imports.
- Implicit relative imports are not supported. (Support for these was removed in Python 3)

**Weak points and other points to consider:**
1. No tests have been created for the Solver_Py-functions is_module() and is_package(). I couldn't figure out how to access the test_files/py-files from the unit tests.
2. Multiple paths or system imports most likely won't work since only one path is considered as the absolute root.
3. cmd_line/test_py.py fails on line 223 when asserting that nodes occur as often in the test-arrays in the XML output. I couldn't find the reason nor a way to fix this error.
4. No custom options exist. One idea would be to support implicit imports if project is Python 2.
5. The code may not in all places follow stylistic guidelines. I apologize.

I am thankful for any feedback on improvements.

I would also be curious to know if you find the graphs generated accurate. There were some assumptions as to how it should look from my side. I hope to see if anyone agrees/disagrees on the results that are generated.

### CODE REVIEW

**Comment by feddischson** [comment]
Ok thanks a lot for your contribution, I will have a look at your code in 2-3 weeks and merge it with the ruby extension.

**Comment by feddischson** [comment]
Hi,

I found some time to have a look at your implementation and I have some feedback and one question.

First some small points:
 - The failure you've mentioned (cmd_line/test_py.py on line 223) is fixed, there have been two issues in `statement_detector.cpp` (see c522bd7 and 21a6dde)
 - Regarding the style guide: I am using clang-format (https://clang.llvm.org/docs/ClangFormat.html) with `code_style='google'`. This tool it is pretty easy to use and to get well formatted code. There are usually some possibilities to use it within your favourite editor / IDE.
 - I've extended `test_statement_detector.cpp` to find the failure mentioned above.
 - There is a clang-tidy build target, which you might use to improve some points, just do `make clang-tidy` and have a loot at `clang-tidy.log`.


There is one point where I want to understand your decision.
In `test/test_files/file1.py` line 2 and 3: As the comment says, these two statements have no effect.
This is because of regular packages supported up to Python 3.2 correct?
```
Python defines two types of packages, regular packages and namespace packages. Regular packages 
are traditional packages as they existed in Python 3.2 and earlier. A regular package is typically 
implemented as a directory containing an __init__.py file. When a regular package is imported, this 
__init__.py file is implicitly executed, and the objects it defines are bound to names in the package’s 
namespace. 
```
(https://docs.python.org/3/reference/import.html -> 5.2.1)
So this means that only code for > Python 3.2 is supported, right?

Would you be able to have a look at the clang-tidy.log?
If yes, please pull my changes (the two bug-fixes, style improvement ...) from the branch `multi_language_py` and pus it again to `multi_language_py`.

**Comment by Chippyri** [comment]
Hello again!
Thank you for taking your time to have a look, I appreciate it. I have not previously used Clang so I will try it out!

> There is one point where I want to understand your decision.
In test/test_files/file1.py line 2 and 3: As the comment says, these two statements have no effect.
This is because of regular packages supported up to Python 3.2 correct?

This is an important question. I did not have in mind that only packages up to 3.2 should be supported, but I hope I am not contradicting myself. Only implicit relative imports should not be supported (which works in Python 2).

I was under the assumption that if you import just a package in this form it would have no effect:

```
# Package imports that have no effect
import pack1
import pack2 as p2
```


However, as you proved with your quote, my assumption is incorrect. \_\_init\_\_.py will be implicitly executed. Edges should be created to from file1.py to pack1/\_\_init\_\_.py and pack2/\_\_init\_\_.py.

I will pull your changes and hopefully have these done this week:
- Use Clang to tidy up/follow code standards
- Modify package import behaviour to create an edge to package \_\_init\_\_.py (vs. no effect)
- Update tests

**Comment by feddischson** [comment]
Thanks a lot for your willingness to do some further progress.

The implemented behaviour might be correct.
And it would be ok, to support Python code > v3.2.

I think it would make sense that you add some small dummy example code test files under `test/test_files/py`. With this example code, you can investigate the behaviour (with different python versions) a bit better before changing the implementation.

It would be good if you can document the result of the investigation in `doc/lang/python.md`.

**Pull request merged**
